name: CI/CD

on:
    push:

permissions:
    contents: write

env:
    TEST_TIMEOUT: 5m

jobs:
    test:
        timeout-minutes: 60
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-2019]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Disable Windows Defender
              if: matrix.os == 'windows-os'
              run: Set-MpPreference -DisableRealtimeMonitoring $true
              shell: powershell
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install extension dependencies
              run: yarn install
            - name: Run tests
              uses: coactions/setup-xvfb@v1
              with:
                  run: yarn test

    package:
        name: Package extension
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install extension dependencies
              run: yarn install
            - name: Package extension
              run: npx @vscode/vsce package --yarn --githubBranch ${{ github.ref_name }}
            - name: Upload extension
              uses: actions/upload-artifact@v3
              with:
                  name: code-blocks-${{ github.ref_name }}.vsix
                  path: code-blocks-*.vsix

    release:
        name: Release extension
        if: startsWith(github.ref, 'refs/tags/v')
        needs: package
        runs-on: ubuntu-latest
        steps:
            - name: Download package
              uses: actions/download-artifact@v3
              with:
                  name: code-blocks-${{ github.ref_name }}.vsix
                  path: .
            - name: Publish GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  generate_release_notes: true
                  files: code-blocks-*.vsix
            # - name: Publish GitHub release
            #   run: npx @vscode/vsce publish -i $(ls code-blocks-*.vsix)
