name: vscode-extension CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "vscode-extension-v*.*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    working-directory: vscode-extension

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install extension dependencies
        run: yarn run install:all
      - name: Test
        run: yarn run pretest

  release:
    name: Release extension
    if: startsWith(github.ref, 'refs/tags/vscode-extension-v')
    needs: test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install vsce
        run: npm i -g vsce
      - name: Install extension dependencies
        run: yarn install
      - name: Build extension
        run: vsce package --yarn
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: vscode-extension/code-blocks-*.vsix
